# Generated by Django 2.2.6 on 2019-10-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0002_studentinfo_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='classes_begin_date',
            field=models.DateField(blank=True, default='2019-09-01', null=True, verbose_name='开班时间'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='is_delete',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否删除'),
        ),
    ]
